version: '3.7'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: alexandrsakulin/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_static:/app/backend_static/
      - foodgram_media:/app/backend_media/
      - db_data:/app/db_data/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: alexandrsakulin/foodgram_frontend:latest
    restart: always
    volumes:
      - ./frontend:/app/result_build/
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
    depends_on:
      - frontend

volumes:
  foodgram_static:
  foodgram_media:
  db_data: