version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: alexandrsakulin/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app_back/static/
      - media_value:/app_back/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: alexandrsakulin/foodgram_frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8000:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  pgdata:
  static_value:
  media_value:

