MAX_LENGTH_EMAIL = 254

MAX_LENGTH_USERNAME = 150

MAX_LENGTH_AUTHOR = 200

MAX_LENGTH_CONFIRMATION_CODE = 100

MAX_LENGTH_RECIPE_NAME = 155

MAX_LENGTH_TAG_COLOR = 7

MAX_LENGTH_TAG_NAME = 200

MAX_LENGTH_TAG_SLUG = 200

MAX_LENGTH_INGREDIENT_NAME = 255

MAX_LENGTH_INGREDIENT_MEAUNIT = 155

MIN_TIME_COOKING = 1

MAX_TIME_COOKING = 32767

MIN_AMOUNT_INGRIDIENTS = 1

MAX_AMOUNT_INGRIDIENTS = 100
