# Generated by Django 3.2.9 on 2023-08-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
