# Generated by Django 3.2.9 on 2023-08-04 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Не менее 1'), django.core.validators.MaxValueValidator(32767, 'Не более 32767')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть не менее 1 минуты!'), django.core.validators.MaxValueValidator(32767, 'Время приготовления должно быть не более 32767 минут!')], verbose_name='Время приготовления (минут)'),
        ),
    ]
