# Generated by Django 3.2.9 on 2023-08-07 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя должно соответсвовать критериям', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
